### ISSUE TITLE
create docker container ?

### ISSUE THREAD

**Issue by dancekid** [alexandre-abrioux/golem-node#25] opened 2022-12-29 21:53 UTC
Hello Alexandre,

tried to create a container but getting errors running the node.

Is there an explanation available somewhere ?

docker run -d \
  --name golem-network \
  --restart=unless-stopped\
  -v /mnt/golem/ya-provider/:/root/.local/share/ya-provider/ \
  -v /mnt/golem/yagna/:/root/.local/share/yagna/ \
  --device /dev/kvm:/dev/kvm \
  -e YA_PAYMENT_NETWORK=testnet \
  -e YA_ACCOUNT=0xcdthdthrth (changed) \
  aabrioux/golem-node:latest

Error:
ERROR golemsp] EOF

**Comment by alexandre-abrioux** [comment] 2022-12-29 23:38
Hi, I'm not sure what the problem is, but I would bet on a volume mount issue. Make sure that the directories you're mounting can be accessed by the process. I would look at this: `/mnt/golem/` --> are you mounting in docker a shared device or network drive? I'd say try with a normal directory first.

**Comment by alexandre-abrioux** [comment] 2023-01-06 19:43
I'm closing this as I suspect it relates more to specific docker config/usage rather than a bug on this image. Please let me know if you think otherwise.

**Closed by alexandre-abrioux** 2023-01-06 19:43 UTC

**Comment by dancekid** [comment] 2023-01-08 16:28
Hello Alex,
i mounted a fixed SATA-SSD and created golem directory. no networkdevice

**Comment by dancekid** [comment] 2023-01-08 17:04
i tried your docker compose file now. I am still a beginner.
how to open firsttime config in docker ? 

in docker compose i get error:
[+] Running 1/1
 ⠿ Container golem_node  Recreated                                                                                                                                                                                                      0.1s
Attaching to golem_node
golem_node  | [2023-01-08T17:02:06Z ERROR golemsp] EOF
golem_node exited with code 0
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
golem_node exited with code 1
